services:
  teletok:
    image: possumm/telefanso:latest
    pull_policy: always
    env_file:
      - stack.env
    restart: unless-stopped
    deploy:
      replicas: 1
    labels:
      - "com.docker.stack.namespace=teletok"
