services:
  teletok:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - stack.dev.env
    volumes:
      - ./app:/code/app # Add volume for hot-reloading
      - teletok-session-dev:/data # Persist the Instagram session between restarts
    restart: "no" # Don't automatically restart in development

volumes:
  teletok-session-dev:
